// Generated by Haxe 4.2.0
(function ($global) { "use strict";
var Macros = function() { };
var MasterCompiler = function() { };
MasterCompiler.main = function() {
	var ba = "12";
	var be = "42";
	console.log("src/MasterCompiler.hx:5:",ba + "\n\n" + be + "\n\n" + ba);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
MasterCompiler.main();
})({});
